spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.capstone.su26_sep490_g2_be: INFO
    org.springframework.security: WARN
